name: Greetings

on: [push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps :
      - name : secret-message    
        uses : actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Message that will be displayed on users' first issue"
          pr-message: "Message that will be displayed on users' first pull request"

      - name: Use GitHub Token
        env:
          MY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "My GitHub token is $MY_TOKEN"

